name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Name of tag in XRPLF/rippled
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # To make a release and upload artifacts.
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install Conan
        run: |
          pip install 'conan<2'
      - uses: actions/checkout@v4
        with:
          repository: xrplf/rippled
          ref: ${{ inputs.tag }}
      - name: authenticate to Redirectory
        run: |
          conan remote add github https://conan.jfreeman.dev
          conan user --remote github ${{ github.repository_owner }} --password ${{ github.token }}
      - name: upload to Redirectory
        run: |
          reference=xrpl/${{ inputs.tag }}@github/${{ github.repository_owner }}
          conan export . ${reference}
          conan upload --remote github ${reference} --confirm
